### ISSUE TITLE
exception handling granularity

### ISSUE THREAD

**Issue by YounesOMK** [seatsio/seatsio-python#95]
currently the SDK provides only two exceptions:
- SeatsioException
- RateLimitExceededException

This forces consumers (i guess) to rely on string matching of error messages to determine the type of error:

```
try:
    client.events.book_best_available()
except SeatsioException as e:
    if "Best available objects not found" in str(e):
        # Handle no available seats
    elif "does not exist" in str(e):
```
why not  implementing typed exceptions for common error cases
```
class SeatsioException(Exception): pass
class SeatsioNoBestAvailableError(SeatsioException): pass
...
```

**Comment by bverbeken** [comment]
It's not clear to me what other types of exceptions you would be able to get in your example? I mean, either the `client.events.book_best_available()` succeeds, or it does not. And the client only needs to handle those two cases imho, I'm not even sure the seats.io API exposes the reason why a best available call failed.  

Of course, the reason why something fails is always useful for debugging purposes, but in that case error messages are clearly sufficient. 

And so, to answer your question: because we like to keep things simple, and to minimise the chances of client code catching/handling the wrong exception type.

**Comment by YounesOMK** [comment]
@bverbeken 
> And so, to answer your question: because we like to keep things simple, and to minimise the chances of client code catching/handling the wrong exception type.

i think string parsing of error messages is much more likely to cause wrong error handling 

```
# current approach - IDE can't help with exception suggestions, it also breaks if api error messages change

try:
    client.events.book_best_available()
except SeatsioException as e:
    if "Best available objects not found" in str(e):
        display_no_seats_message()
    elif "event not found" in str(e):
        notify_admin_invalid_event()
    elif something else:
       ...
```

```
# with typed exceptions - IDE shows all possible errors, stable if messages change
try:
    client.events.book_best_available()
except SeatsioNoBestAvailableError:
    display_no_seats_message()
except SeatsioNotFoundError:
    notify_admin_invalid_event()
```

**Comment by bverbeken** [comment]
> i think string parsing of error messages is much more likely to cause wrong error handling

Of course. I'm not saying you should parse error messages. I am saying it's usually not necessary to handle different error responses differently. 

That said, your example does help. If I understand correctly, it seems you want to be able to distinguish between "there are no free seats left" and "other (technical) errors, like for instance event not found". 
That's a valid concern, which I'll take to the team. 

I'm closing this issue for now, but feel free to reach out to support@seats.io for further discussion or in case of questions 👍

**Comment by bverbeken** [comment]
Update: version [v81.0.0](https://github.com/seatsio/seatsio-python/releases/tag/v81.0.0) now throws a specific exception type when best available objects are not found.
